// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://teauqzorqvpuprtdxxcs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRlYXVxem9ycXZwdXBydGR4eGNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4ODEzMjMsImV4cCI6MjA2NzQ1NzMyM30.9sw9_XgnZSfoV_JjSA8VPz4haIev13wZF8k4w3w_8sA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});